name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - uses: aiken-lang/setup-aiken@v0.1.0
        with:
          version: v1.1.9

      - run: aiken fmt --check
      - run: aiken c
      - run: aiken b
